import { useState, useMemo } from 'react'
import { useFirestoreDoc } from '../hooks/useFirestoreData'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Search, Upload, Download } from 'lucide-react'

interface FrequencyData {
  terms: string[]
  courses: Record<string, string[]>
}

type Pattern = 'Every semester' | 'Fall only' | 'Spring only' | 'Most semesters' | 'Occasional' | 'New / Rare'

function classifyPattern(appearances: string[], allTerms: string[]): Pattern {
  const count = appearances.length
  const total = allTerms.length
  if (count === 0) return 'New / Rare'

  const falls = appearances.filter(t => t.startsWith('Fall'))
  const springs = appearances.filter(t => t.startsWith('Spring'))
  const totalFalls = allTerms.filter(t => t.startsWith('Fall')).length
  const totalSprings = allTerms.filter(t => t.startsWith('Spring')).length

  if (count === total) return 'Every semester'
  if (count >= total * 0.8) return 'Most semesters'
  if (falls.length === totalFalls && springs.length === 0) return 'Fall only'
  if (springs.length === totalSprings && falls.length === 0) return 'Spring only'
  if (count <= 1) return 'New / Rare'
  return 'Occasional'
}

const PATTERN_COLORS: Record<Pattern, string> = {
  'Every semester': 'bg-emerald-100 text-emerald-800',
  'Most semesters': 'bg-blue-100 text-blue-800',
  'Fall only': 'bg-amber-100 text-amber-800',
  'Spring only': 'bg-violet-100 text-violet-800',
  'Occasional': 'bg-slate-100 text-slate-800',
  'New / Rare': 'bg-rose-100 text-rose-800',
}

export function FrequencyTracker() {
  const { data, loading, error, save } = useFirestoreDoc<FrequencyData>(
    'dcda_config',
    'frequency'
  )
  const [search, setSearch] = useState('')
  const [patternFilter, setPatternFilter] = useState<Pattern | 'all'>('all')

  const frequency = useMemo(() => data ?? { terms: [], courses: {} }, [data])

  const rows = useMemo(() => {
    const entries = Object.entries(frequency.courses).map(([code, terms]) => ({
      code,
      terms,
      pattern: classifyPattern(terms, frequency.terms),
      count: terms.length,
    }))

    let filtered = entries
    if (search) {
      const q = search.toLowerCase()
      filtered = filtered.filter(r => r.code.toLowerCase().includes(q))
    }
    if (patternFilter !== 'all') {
      filtered = filtered.filter(r => r.pattern === patternFilter)
    }

    return filtered.sort((a, b) => {
      if (b.count !== a.count) return b.count - a.count
      return a.code.localeCompare(b.code)
    })
  }, [frequency, search, patternFilter])

  const patternCounts = useMemo(() => {
    const counts: Record<string, number> = {}
    for (const code of Object.keys(frequency.courses)) {
      const p = classifyPattern(frequency.courses[code], frequency.terms)
      counts[p] = (counts[p] || 0) + 1
    }
    return counts
  }, [frequency])

  const handleExport = () => {
    const blob = new Blob([JSON.stringify(frequency, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'course-frequency.json'
    a.click()
    URL.revokeObjectURL(url)
  }

  const handleImport = () => {
    const input = document.createElement('input')
    input.type = 'file'
    input.accept = '.json'
    input.onchange = async (e) => {
      const file = (e.target as HTMLInputElement).files?.[0]
      if (!file) return
      try {
        const text = await file.text()
        const imported = JSON.parse(text) as FrequencyData
        if (!Array.isArray(imported.terms) || typeof imported.courses !== 'object') {
          alert('Invalid frequency JSON format. Expected { terms: [...], courses: { ... } }')
          return
        }
        await save(imported)
      } catch {
        alert('Failed to parse JSON file')
      }
    }
    input.click()
  }

  if (loading) {
    return <div className="text-muted-foreground py-12 text-center">Loading frequency data...</div>
  }

  if (error) {
    return <div className="text-destructive py-12 text-center">{error}</div>
  }

  if (frequency.terms.length === 0) {
    return (
      <div className="space-y-4 py-12 text-center">
        <p className="text-muted-foreground">No frequency data yet.</p>
        <p className="text-sm text-muted-foreground">
          Import <code>course-frequency.json</code> generated by the scraper.
        </p>
        <Button variant="outline" onClick={handleImport} className="gap-1">
          <Upload className="size-4" />
          Import
        </Button>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-semibold">Course Frequency</h2>
          <p className="text-sm text-muted-foreground mt-1">
            {Object.keys(frequency.courses).length} courses tracked across {frequency.terms.length} semesters
            ({frequency.terms[0]} — {frequency.terms[frequency.terms.length - 1]})
          </p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={handleExport} className="gap-1">
            <Download className="size-4" />
            Export
          </Button>
          <Button variant="outline" size="sm" onClick={handleImport} className="gap-1">
            <Upload className="size-4" />
            Import
          </Button>
        </div>
      </div>

      {/* Pattern summary cards */}
      <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-6 gap-3">
        {(Object.keys(PATTERN_COLORS) as Pattern[]).map((pattern) => (
          <button
            key={pattern}
            type="button"
            onClick={() => setPatternFilter(patternFilter === pattern ? 'all' : pattern)}
            className={`rounded-lg p-3 text-center transition-all border ${
              patternFilter === pattern
                ? 'ring-2 ring-primary border-primary'
                : patternFilter === 'all'
                  ? 'border-transparent'
                  : 'opacity-40 border-transparent'
            } ${PATTERN_COLORS[pattern]}`}
          >
            <div className="text-2xl font-bold">{patternCounts[pattern] || 0}</div>
            <div className="text-xs font-medium mt-0.5">{pattern}</div>
          </button>
        ))}
      </div>

      {/* Search */}
      <div className="relative">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-muted-foreground" />
        <Input
          placeholder="Search courses..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="pl-10 h-10 text-sm"
        />
      </div>

      {/* Heatmap table */}
      <div className="border rounded-lg overflow-x-auto">
        <table className="w-full text-sm">
          <thead className="bg-muted/50">
            <tr>
              <th className="text-left px-4 py-2 font-medium sticky left-0 bg-muted/50">Course</th>
              {frequency.terms.map((term) => (
                <th key={term} className="px-3 py-2 font-medium text-center whitespace-nowrap">
                  {term.replace('Spring ', 'Sp ').replace('Fall ', 'Fa ').replace('Summer ', 'Su ')}
                </th>
              ))}
              <th className="text-left px-4 py-2 font-medium">Pattern</th>
              <th className="text-center px-3 py-2 font-medium">Count</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((row) => (
              <tr key={row.code} className="border-t hover:bg-muted/30">
                <td className="px-4 py-2 font-mono sticky left-0 bg-background">{row.code}</td>
                {frequency.terms.map((term) => {
                  const offered = row.terms.includes(term)
                  return (
                    <td key={term} className="px-3 py-2 text-center">
                      <div
                        className={`mx-auto size-5 rounded ${
                          offered ? 'bg-primary' : 'bg-muted'
                        }`}
                        title={offered ? `Offered ${term}` : `Not offered ${term}`}
                      />
                    </td>
                  )
                })}
                <td className="px-4 py-2">
                  <span className={`inline-block px-2 py-0.5 rounded text-xs font-medium ${PATTERN_COLORS[row.pattern]}`}>
                    {row.pattern}
                  </span>
                </td>
                <td className="px-3 py-2 text-center text-muted-foreground">
                  {row.count}/{frequency.terms.length}
                </td>
              </tr>
            ))}
            {rows.length === 0 && (
              <tr>
                <td colSpan={frequency.terms.length + 3} className="text-center py-8 text-muted-foreground">
                  No courses match your filter.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  )
}
